services:
  app:
    build: .
    container_name: wish_list_app
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=${PYTHONUNBUFFERED}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/api/health"]
      interval: 5s
      timeout: 5s
      retries: 10
    profiles: ["prod"]

  postgres:
    image: postgres:16
    container_name: wish_list_db
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10
    profiles: ["prod", "dev"]

  pgadmin:
    image: dpage/pgadmin4:8.12
    container_name: wish_list_pg_admin
    restart: unless-stopped
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
      - PGADMIN_CONFIG_SERVER_MODE=False
      - PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED=False
    ports:
      - "5050:80"
    volumes:
      - ./volumes/pgadmin:/var/lib/pgadmin
    depends_on:
      postgres:
        condition: service_healthy
    profiles: ["dev"]
